Repository OSLL/os-hse-1h2019, pull requests merged in 2019-06, with the labels that each got.

#47 add lab_02 Palchenkova
  solutions/pal/lab2/kern/kdebug.c
  solutions/pal/lab2/kern/monitor.c
  solutions/pal/lab2/kern/pmap.c
  solutions/pal/lab2/lib/printfmt.c
Labels: fixed

#49 lab2 done
  solutions/nik/lab2/kern/kdebug.c
  solutions/nik/lab2/kern/monitor.c
  solutions/nik/lab2/kern/pmap.c
  solutions/nik/lab2/lib/printfmt.c
Labels: changes_requested

#62 Epi lab3
  solutions/epi/lab3/kern/env.c
  solutions/epi/lab3/kern/init.c
  solutions/epi/lab3/kern/kdebug.c
  solutions/epi/lab3/kern/monitor.c
  solutions/epi/lab3/kern/monitor.h
  solutions/epi/lab3/kern/pmap.c
  solutions/epi/lab3/kern/syscall.c
  solutions/epi/lab3/kern/trap.c
  solutions/epi/lab3/kern/trapentry.S
  solutions/epi/lab3/lib/libmain.c
Labels: fixed

#107 lab3 Malysheva
  solutions/mal/lab3/GNUmakefile
  solutions/mal/lab3/conf/env.mk
  solutions/mal/lab3/kern/env.c
  solutions/mal/lab3/kern/kdebug.c
  solutions/mal/lab3/kern/monitor.c
  solutions/mal/lab3/kern/pmap.c
  solutions/mal/lab3/kern/syscall.c
  solutions/mal/lab3/kern/trap.c
  solutions/mal/lab3/kern/trapentry.S
  solutions/mal/lab3/lib/libmain.c
  solutions/mal/lab3/lib/printfmt.c
Labels: maybe

#78 kra lab3
  solutions/kra/lab3/kern/env.c
  solutions/kra/lab3/kern/kdebug.c
  solutions/kra/lab3/kern/monitor.c
  solutions/kra/lab3/kern/pmap.c
  solutions/kra/lab3/kern/syscall.c
  solutions/kra/lab3/kern/trap.c
  solutions/kra/lab3/kern/trapentry.S
  solutions/kra/lab3/lib/libmain.c
  solutions/kra/lab3/lib/printfmt.c
Labels: fixed
